;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Interaction",DevComment="Fired when the player presses the Interact button")
+GameplayTagList=(Tag="Item",DevComment="ItemTagsDefinition")
+GameplayTagList=(Tag="Item.Equipment",DevComment="Items that character can equip i.e. chest, helmet, sword")
+GameplayTagList=(Tag="Item.Equipment.Weapon.Sword",DevComment="sword")
+GameplayTagList=(Tag="Item.Materials",DevComment="Materials i.e. Wood, Stone")
+GameplayTagList=(Tag="Item.Materials.Wood",DevComment="wood")

